### ISSUE TITLE
PascalCase

### ISSUE THREAD

**Issue by eloekset** [johnkors/NoCommonsNET#10]
This is ported from Java, and has a naming convention that differs from most .NET libraries. Methods should have PascalCase naming. It would be a quite easy change, but breaking change, which should go into a major version on NuGet. Apart from that, is there any reason not to follow default naming convention?

**Comment by johnkors** [comment]
No, you're absolutely right. This was a raw hatchet job at the time of porting. I've tried to keep it as close to the Java source as possible for ease of later porting of upstream changes in the Java repo, but other than that no reason.
